# Site settings
title: Wizard of Ads
email: sales@wizardofads.uk
description: > # this means to ignore newlines until "baseurl:"
baseurl: "wizardofads1" # the subpath of your site, e.g. /blog/
url: "wizardofads1.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: wizardofads1

# Build settings
markdown: kramdown
