# Site settings
title: Wizard of Ads
email: iborisov@wizardofads.uk
description: > # this means to ignore newlines until "baseurl:"
baseurl: "wizardofads.uk" # the subpath of your site, e.g. /blog/
url: "wizardofads.uk" # the base hostname & protocol for your site

twitter_username:
github_username: wizardofads1

# Build settings
markdown: kramdown
